apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ops-control-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ankitbiswal141/Ops-Control-Portal.git
    targetRevision: HEAD
    path: deployments/cloud/  # <--- UPDATED PATH
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true