# 1. BACKEND DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-portal-backend
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ops-portal-backend
  template:
    metadata:
      labels:
        app: ops-portal-backend
    spec:
      containers:
      - name: backend
        image: ${{ secrets.DOCKERHUB_USERNAME }}/ops-portal-backend:${{ github.sha }}
        env:
            - name: ARGOCD_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argo-secrets  # Must match the name in argocd.tf
                  key: ARGOCD_AUTH_TOKEN
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        envFrom:
        - secretRef:
            name: argo-secrets

---
# 3. FRONTEND DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-portal-frontend
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ops-portal-frontend
  template:
    metadata:
      labels:
        app: ops-portal-frontend
    spec:
      containers:
      - name: frontend
        image: ankitbiswal/ops-frontend:802a15f1c2c50a0f92c0a40ab507bdf7f068b729
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
